development:
  adapter: postgresql
  encoding: unicode
  database: my_twitter_development
  pool: 5
  username: my_twitter
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: my_twitter_test
  pool: 5
  username: my_twitter
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: my_twitter_production
  pool: 5
  username: my_twitter
  password:
